version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: instagram_postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - instagram_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: instagram_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - instagram_network

volumes:
  postgres_data:

networks:
  instagram_network:
    driver: bridge
